package com.event_website.Dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Basic statistical summary of an event including ticket sales and revenue.")
public class EventSimpleStatDTO {

    @Schema(description = "Unique identifier of the event", example = "42")
    private Integer eventId;

    @Schema(description = "Name of the event", example = "Music Festival 2025")
    private String eventName;

    @Schema(description = "Total number of tickets sold for the event", example = "1200")
    private long ticketsSold;

    @Schema(description = "Total revenue generated by the event", example = "360000.00")
    private BigDecimal revenue;
}
