name: my first workflow

on: push

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: omar

      - name: prints first
        run: echo 'first'

      - name: lists files
        run: ls -l

      - name: read gitignore
        run: cat .gitignore
